# -*- coding: utf-8 -*-
"""image augumentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KKPJHUtvNF_AzrUiylXh_Husb19JYMzE
"""

from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator
from matplotlib import pyplot as plt

!wget https://epi.azureedge.net/website-images/images/default-album/siberian-husky.jpg?sfvrsn=19bfd37b_2

img = load_img("siberian-husky.jpg?sfvrsn=19bfd37b_2")

data = img_to_array(img)

samples = expand_dims(data,0)

datagen = ImageDataGenerator(horizontal_flip=True, vertical_flip=True, rotation_range=90)

"""prepare itrator"""

it = datagen.flow(samples, batch_size=1)

"""generate samples and plot"""

for i in range(9):
  #define subplot
  plt.subplot(330+1+i)
  #generate batch of images
  batch=it.next()
  #convert to unsigned numbers for viewing
  image = batch[0].astype('uint8')
  #plot raw pixel data
  plt.imshow(image)

plt.show()